# Generated by Django 2.2.1 on 2019-05-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='jbo_main.jpeg', upload_to='profile_pics'),
        ),
    ]
