# Generated by Django 2.2.1 on 2019-06-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190530_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='jbouser',
            name='slug',
            field=models.SlugField(default='shane-curtis', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/JBO_main.png', upload_to='profile_pics'),
        ),
    ]
