# Generated by Django 2.2.1 on 2019-06-06 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190604_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='player_card',
            field=models.ImageField(blank=True, upload_to='player_cards'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 9, 7, 37, 48, 566170, tzinfo=utc)),
        ),
    ]
