# Generated by Django 2.2.1 on 2019-06-07 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190606_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='player_card',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 1, 18, 30, 364419, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='player_cards')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Participant')),
            ],
        ),
    ]
