# Generated by Django 2.2.1 on 2019-06-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='treetops-premier', unique=True),
            preserve_default=False,
        ),
    ]
